### ISSUE TITLE
Switch to ESM and require node v12.20

### ISSUE THREAD

**Issue by jimmywarting** [jsdom/tr46#32]
time to switch require for import?

**Comment by domenic** [comment]
No. Then whatwg-url would need to switch or import async, which would have the same effect on jsdom, which is infeasible.

**Comment by jimmywarting** [comment]
Got to start somewhere?
How about switching jsdom to ESM first then? NodeJS can still require commonjs files.

**Comment by domenic** [comment]
Nah.
