### ISSUE TITLE
Remove "punycode" dependency as it is deprecated.

### ISSUE THREAD

**Issue by AcclaimedAP** [jsdom/tr46#51]
Punycode is deprecated.

```
(node:53980) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
```
It's imported here:
https://github.com/jsdom/tr46/blob/d6cd9a73bb9eb4b3defb50c348db2a60704d1367/index.js#L3

`const punycode = require("punycode/");`

It's also used a few times inside of the index.js file.

**Comment by AcclaimedAP** [comment]
It isn't a huge issue, as it isn't causing any issues for me, it is mostly a potential issue for the future.

If you're encountering this issue, you can run node with the `--no-deprecation` flag, and hopefully it will be fine.

**Comment by domenic** [comment]
This package depends on npm punycode, not built-in punycode, so cannot cause the issue you are seeing.
