### ISSUE TITLE
toAscii and Unicode tests are failing

### ISSUE THREAD

**Issue by 0x70b1a5** [jsdom/tr46#55]
### Description

Two tests fail.

```
✖ failing tests:

✖ /home/../tr46/test/toascii.js (95.585125ms)
  Error [ERR_TAP_LEXER_ERROR]: Unexpected character: ‍ at line 1, column 0
      at Socket.emit (node:events:511:28) {
    code: 'ERR_TAP_LEXER_ERROR'
  }

✖ /home/../tr46/test/unicode.js (288.905067ms)
  Error [ERR_TAP_LEXER_ERROR]: Unexpected character: ̀ at line 1, column 0
      at Socket.emit (node:events:511:28) {
    code: 'ERR_TAP_LEXER_ERROR'
  }

```

### Reproduce

1. Clone tr46.
2. `npm run test`
3. Verify failing tests.

**Comment by domenic** [comment]
Based on searching for `ERR_TAP_LEXER_ERROR` on Google this may have been an issue fixed by newer Node.js versions; I suggest updating to the latest and trying again. Notice how the tests all pass on continuous integration.
