### ISSUE TITLE
Missing LICENSE file in the repo of ver 0.0.3

### ISSUE THREAD

**Issue by itsuki-murata** [jsdom/tr46#58]
Currently I'm using tr46 version 0.0.3, but can't find a LICENSE file in the repo of ver 0.0.3.
Could you add the LICENSE file in the repo of ver 0.0.3?
Or is it possible to use the LICENSE file of the latest version as the license for ver 0.0.3?
Thanks in advance.

**Comment by domenic** [comment]
Version 0.0.3 is not supported. I suggest upgrading.

**Comment by itsuki-murata** [comment]
Thank you for your reply.
I'll consider upgrading.
Thank you.
