### ISSUE TITLE
Deprecation issue with the 'punycode' module

### ISSUE THREAD

**Issue by valorisa** [jsdom/tr46#62]
Hello,

I am encountering a deprecation issue with the punycode module in your project. The warning message is as follows:

(node:19880) [DEP0040] DeprecationWarning: The punycode module is deprecated. Please use a userland alternative instead.

Could you consider updating your project to use a more recent version of punycode (e.g., punycode@2.3.1)?

Thank you in advance for your help.

Best regards,
valorisa

**Comment by domenic** [comment]
This is not related to this project.
